[package]
name = "cve-ingest-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["stream", "json", "blocking"] }
chrono = "0.4.31"
jsonit = "0.2.3"
flate2 = "1.0"
itertools = "0.12.0"
ijson = "0.1.3"
rocksdb = "0.20.1"
bytevec = "0.2.0"
sha1 = "0.10.6"


[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
