[package]
name = "cve-ingest-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["stream", "json", "blocking"] }
# futures-util = "0.3.26"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.31"
jsonit = "0.2.2"
async-compression = { version = "0.4.4", features = ["gzip", "futures-io", "tokio"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
futures = { version = "0.3.29"}
destream_json = "0.12.0"
flate2 = "1.0"

pipe = "0.4.0"
async-std = "1.12.0"
# ijson = {git = "https://github.com/isagalaev/ijson-rust.git"}

[dependencies.mongodb]
version = "2.7.1"
default-features = false
features = ["async-std-runtime"]